name: connect-test-local.yml

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  install:
    timeout-minutes: 10
    runs-on: [testing]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: '20'
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - uses: actions/cache@v2
        name: Cache Cargo registry + index
        id: cache-rust
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: cargo-${{ runner.os }}-v0000-${{ hashFiles('**/Cargo.lock') }}
      - name: run cargo test
        run: |
          cargo test
          cargo run &
      - name: install packages
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: |
          pnpm install
        working-directory: ./sdk
      - name: test base
        run: |
          pnpm test:run
        working-directory: ./sdk/apps/base
      - name: test solana
        run: |
          pnpm test:run
        working-directory: ./sdk/apps/base
